"use client";
import Link from "next/link";
import {useState} from "react";

const cases=[
 {name:"唐代群像中的袍服",image:"/content/images/tang/09b395e5-8fe3-4fac-9895-736b738bd25f.png",range:"唐代目录图像",object:"画面左侧红袍男性人物",visible:"可观察首服、领部、衣长与整体组合；局部纹样不可辨。",source:"作品名称、作者、收藏机构待补",citation:"《旧唐书·舆服》中的“白袍、靴、起梁带”可作为同类名物线索，不能直接证明画中服饰名称。",parts:[{name:"首服",note:"具体名称仍需作品著录支持。",x:"29%",y:"25%"},{name:"领与上身",note:"原图分辨率不足以确认领型细节。",x:"28%",y:"39%"},{name:"袍身下部",note:"可观察衣长和整体轮廓。",x:"28%",y:"67%"}],words:[["袍","pao"],["带","dai"],["靴","xue"]]},
 {name:"明代官员画像中的袍服",image:"/content/images/ming/0fd590a9-35ae-4dd2-b202-ffe8224d0e35.png",range:"明代目录图像",object:"戴帽、着红色圆领长袍的男性人物",visible:"圆领、宽袖、长袍轮廓清楚；胸前纹样需查看更高分辨率原图。",source:"画像名称、人物身份、收藏机构待补",citation:"可与明代冠服制度文献对读；来源未核定前，不直接命名官帽和袍服等级。",parts:[{name:"官帽",note:"具体名称需结合画像著录与制度文献确认。",x:"50%",y:"12%"},{name:"圆领",note:"颈部圆形领口，是较清楚的结构线索。",x:"50%",y:"25%"},{name:"袍袖",note:"宽大的袍袖，可与袍身轮廓一并观察。",x:"22%",y:"56%"}],words:[["袍","pao"],["冠","guan"],["带","dai"]]},
 {name:"清代刺绣袍服实物",image:"/content/images/qing/071cedfe-7d65-4fa5-b73d-f2b434e46d78.png",range:"清代目录实物图",object:"蓝地刺绣长袍实物",visible:"斜襟、宽袖、黑色缘饰、通身花鸟纹样与下摆结构清楚。",source:"藏品名称、年代、馆藏机构与版权待补",citation:"实物可以说明形制和纹样；缺少藏品著录时，不能判断具体服制等级与使用者。",parts:[{name:"领襟",note:"领口与斜襟结构，适合观察裁剪关系。",x:"49%",y:"9%"},{name:"袖端",note:"右侧袖端的黑色缘饰与刺绣边界。",x:"91%",y:"31%"},{name:"下摆",note:"袍服下摆及边缘纹样。",x:"50%",y:"88%"}],words:[["袍","pao"],["锦","jin"],["纹样","wenyang"]]}
];

export function LabContent(){
 const [sample,setSample]=useState(0);const [focus,setFocus]=useState(0);const item=cases[sample];const part=item.parts[focus];
 return <><section className="lab-guide"><b>选择图像</b><i>→</i><b>观察具体部位</b><i>→</i><b>连接服饰词条</b><i>→</i><b>回到史料核对</b></section><section className="lab lab-redesign"><div className="lab-samples"><h2>图像案例</h2><p>只描述画面所见；缺少著录的信息不作确定判断。</p>{cases.map((x,i)=><button className={sample===i?"active":""} onClick={()=>{setSample(i);setFocus(0)}} key={x.name}><span>0{i+1}</span><b>{x.name}</b><small>{x.range}</small></button>)}</div><div className="lab-image verified-image"><img src={item.image} alt={item.name}/>{item.parts.map((x,i)=><button aria-label={`查看${x.name}线索`} className={`ai-marker ${focus===i?"active":""}`} style={{left:x.x,top:x.y}} onClick={()=>setFocus(i)} key={x.name}><span>{i+1}</span>{x.name}</button>)}<div className="focus-note"><small>当前标注</small><b>{part.name}</b><p>{part.note}</p></div></div><aside className="lab-result observation-record"><p className="eyebrow">IMAGE READING</p><h2>图像观察记录</h2><dl><div><dt>观察对象</dt><dd>{item.object}</dd></div><div><dt>图中可见</dt><dd>{item.visible}</dd></div><div><dt>目录信息</dt><dd>{item.range}</dd></div><div><dt>来源状态</dt><dd className="source-pending">{item.source}</dd></div></dl><h3>相关服饰词</h3><div className="recommendations">{item.words.map(([name,id])=><Link key={id} href={`/garments/${id}`}>{name}</Link>)}</div><h3>如何与文献对照</h3><p className="verify-text">{item.citation}</p><div className="result-boundary"><b>可以说明</b><p>图中实际可见的形态、结构与穿着组合。</p><b>暂不能说明</b><p>准确年代、服饰专名、身份等级及与某段古籍的直接对应关系。</p></div><Link className="lab-review-link" href="/contribute">补充作品来源 →</Link></aside></section><section className="ai-caution lab-caution"><b>使用原则</b> 先描述图中所见，再查来源和文献；没有依据的名称、年代与身份不作结论。</section></>
}
